docker_build(
  'example-go-image',
  '.',
  only=['main.go', 'go.mod', 'go.sum'],
  dockerfile='deployments/Dockerfile')

k8s_yaml('deployments/kubernetes.yaml')
k8s_resource('example-go', port_forwards=[8000, 40000])
